-- https://en.wikiquote.org/wiki/Linus_Torvalds
return {
    {
        [[I'm doing a (free) operating system (just a hobby, won't be big and professional like gnu) for 386(486) AT]],
        [[clones.]],
        [[- Linus Torvalds]],
    },
    {
        [[Do you pine for the nice days of minix-1.1, when men were men and wrote their own device drivers?]],
        [[- Linus Torvalds]],
    },
    {
        [[Well, with a subject like this, I'm afraid I'll have to reply. Apologies to minix-users who have heard enough]],
        [[about linux anyway. I'd like to be able to just "ignore the bait", but … time for some serious flamefesting!]],
        [[- Linus Torvalds]],
    },
    {
        [[Your job is being a professor and researcher: That's one hell of a good excuse for some of the brain-damages]],
        [[of Minix.]],
        [[- Linus Torvalds]],
    },
    {
        [[Well, I probably won't get too good grades even without you: I had an argument (completely unrelated – not]],
        [[even pertaining to OS's) with the person here at the university that teaches OS design. I wonder when I'll]],
        [[learn :)]],
        [[- Linus Torvalds]],
    },
    {
        [[No. That's it. The cool name, that is. We worked very hard on creating a name that would appeal to the]],
        [[majority of people, and it certainly paid off: thousands of people are using linux just to be able to say "OS/2?]],
        [[Hah. I've got Linux. What a cool name". 386BSD made the mistake of putting a lot of numbers and weird]],
        [[abbreviations into the name, and is scaring away a lot of people just because it sounds too technical.]],
        [[- Linus Torvalds]],
    },
    {
        [[When you say "I wrote a program that crashed Windows", people just stare at you blankly and say "Hey, I got]],
        [[those with the system, **\*for free\***"]],
        [[- Linus Torvalds]],
    },
    {
        [[If you need more than 3 levels of indentation, you're screwed anyway, and should fix your program.]],
        [[- Linus Torvalds]],
    },
    {
        [[You know you're brilliant, but maybe you'd like to understand what you did 2 weeks from now.]],
        [[- Linus Torvalds]],
    },
    { [[An infinite number of monkeys typing into GNU Emacs would never make a good program.]], [[- Linus Torvalds]] },
    {
        [[It's a bird … it's a plane … no, it's KernelMan, faster than a speeding bullet, to your rescue. Doing new]],
        [[kernel versions in under 5 seconds flat …]],
        [[- Linus Torvalds]],
    },
    {
        [[Some people have told me they don't think a fat penguin really embodies the grace of Linux, which just tells]],
        [[me they have never seen an angry penguin charging at them in excess of 100 mph. They'd be a lot more careful]],
        [[about what they say if they had.]],
        [[- Linus Torvalds]],
    },
    {
        [[See, you not only have to be a good coder to create a system like Linux, you have to be a sneaky bastard]],
        [[too ;-)]],
        [[- Linus Torvalds]],
    },
    { [[Only wimps use tape backup: *real* men just upload their important stuff on ftp]], [[- Linus Torvalds]] },
    {
        [[If you still don't like it, that's OK: that's why I'm boss. I simply know better than you do.]],
        [[- Linus Torvalds]],
    },
    {
        [[…the Linux philosophy is "laugh in the face of danger". Oops. Wrong one. "Do it yourself". That's it.]],
        [[- Linus Torvalds]],
    },
    {
        [[The main reason there are no raw devices [in Linux] is that I personally think that raw devices are a stupid]],
        [[idea.]],
        [[- Linus Torvalds]],
    },
    { [[Making Linux GPL'd was definitely the best thing I ever did.]], [[- Linus Torvalds]] },
    {
        [[(In answer to the question: In the extreme case, if it was just you doing all the code, and the rest of the]],
        [[world quietly used it, would it make sense to give it away free? Unless you're particularly grateful for other]],
        [[free things you've got off the Net, would the answer be No?":)]],
        [[- Linus Torvalds]],
    },
    {
        [["Regression testing"? What's that? If it compiles, it is good; if it boots up, it is perfect.]],
        [[- Linus Torvalds]],
    },
    { [[My name is Linus Torvalds and I am your god.]], [[- Linus Torvalds]] },
    { [[If Microsoft ever does applications for Linux it means I've won.]], [[- Linus Torvalds]] },
    {
        [[I was thrown out of fourth grade because I couldn't write my own name, and it's been all downhill from]],
        [[there.]],
        [[- Linus Torvalds]],
    },
    {
        [[I'd like to say that I knew this would happen, that it's all part of the plan for world domination.]],
        [[- Linus Torvalds]],
    },
    {
        [[Note that nobody reads every post in linux-kernel. In fact, nobody who expects to have time left over to]],
        [[actually do any real kernel work will read even half. Except Alan]],
        [[Cox, but he's actually not human, but about a thousand gnomes working in under-ground caves in Swansea. None of the]],
        [[individual gnomes read all the postings either, they just work together really well.]],
        [[- Linus Torvalds]],
    },
    { [[Talk is cheap. Show me the code.]], [[- Linus Torvalds]] },
    {
        [[I'm a bastard. I have absolutely no clue why people can ever think otherwise. Yet they do. People think I'm a]],
        [[nice guy, and the fact is that I'm a scheming, conniving bastard who doesn't care for any hurt feelings or lost]],
        [[hours of work, if it just results in what I consider to be a better system. And I'm not just saying that. I'm]],
        [[really not a very nice person. I can say "I don't care" with a straight face, and really mean it.]],
        [[- Linus Torvalds]],
    },
    {
        [[Once you realize that documentation should be laughed at, peed upon, put on fire, and just ridiculed in]],
        [[general, THEN, and only then, have you reached the level where you can safely read it and try to use it to]],
        [[actually implement a driver.]],
        [[- Linus Torvalds]],
    },
    {
        [[To kind of explain what Linux is, you have to explain what an operating system is. And the thing about an]],
        [[operating system is that you're never ever supposed to see it. Because nobody really uses an operating system;]],
        [[people use programs on their computer. And the only mission in life of an operating system is to help those]],
        [[programs run. So an operating system never does anything on its own; it's only waiting for the programs to ask]],
        [[for certain resources, or ask for a certain file on the disk, or ask to connect to the outside world. And then]],
        [[the operating system steps in and tries to make it easy for people to write programs.]],
        [[- Linus Torvalds]],
    },
    {
        [[Yeah. And as Linus once said: most numerical problems today in pure CPU cycles are actually 3D games. … It's]],
        [[not "incorrect" to say that you want the result faster, even if that result doesn't match your theoretical]],
        [[models.]],
        [[- Linus Torvalds]],
    },
    { [[In short: just say NO TO DRUGS, and maybe you won't end up like the Hurd people.]], [[- Linus Torvalds]] },
    {
        [[Hey, that's not a bug, that's a FEATURE! You know what the most complex piece of engineering known to man in]],
        [[the whole solar system is? Guess what – it's not Linux, it's not Solaris, and it's not your car. It's you. And]],
        [[me. And think about how you and me actually came about – not through any complex design. Right. "Sheer luck".]],
        [[Well, sheer luck, AND:]],
        [[• Free availability and crosspollination through sharing of "source code", although biologists call it DNA.]],
        [[• A rather unforgiving user environment, that happily replaces bad versions of us with better working versions]],
        [[and thus culls the herd (biologists often call this "survival of the fittest").]],
        [[• Massive undirected parallel development ("trial and error").]],
        [[I'm deadly serious: we humans have _never_ been able to replicate something more complicated than what we]],
        [[ourselves are, yet natural selection did it without even thinking. Don't underestimate the power of survival of]],
        [[the fittest. And don't EVER make the mistake that you can design something better than what you get from]],
        [[ruthless massively parallel trial-and-error with a feedback cycle. That's giving your intelligence much too much]],
        [[credit. ]],
        [[- Linus Torvalds]],
    },
    { [[I allege that SCO is full of it.]], [[- Linus Torvalds]] },
    { [[They are smoking crack.]], [[- Linus Torvalds]] },
    { [[Those that can, do. Those that can't, complain.]], [[- Linus Torvalds]] },
    {
        [[Really, I'm not out to destroy Microsoft. That will just be a completely unintentional side effect.]],
        [[- Linus Torvalds]],
    },
    {
        [[Modern PCs are horrible. ACPI is a complete design disaster in every way. But we're kind of stuck with it. If]],
        [[any Intel people are listening to this and you had anything to do with ACPI, shoot yourself now, before you]],
        [[reproduce.]],
        [[- Linus Torvalds]],
    },
    {
        [[There are literally several levels of SCO being wrong. And even if we were to live in that alternate universe]],
        [[where SCO would be right, they'd still be wrong.]],
        [[- Linus Torvalds]],
    },
    {
        [[Nobody should start to undertake a large project. You start with a small *trivial* project, and you should]],
        [[never expect it to get large. If you do, you'll just overdesign and generally think it is more important than it]],
        [[likely is at that stage. Or worse, you might be scared away by the sheer size of the work you envision. So start]],
        [[small, and think about the details. Don't think about some big picture and fancy design. If it doesn't solve]],
        [[some fairly immediate need, it's almost certainly over-designed. And don't expect people to jump in and help]],
        [[you. That's not how these things work. You need to get something half-way *useful* first, and then others will]],
        [[say "hey, that *almost* works for me", and they'll get involved in the project.]],
        [[- Linus Torvalds]],
    },
    {
        [[Anybody who tells me I can't use a program because it's not open source, go suck on rms. I'm not interested.]],
        [[99% of that I run tends to be open source, but that's *my* choice, dammit.]],
        [[- Linus Torvalds]],
    },
    { [[The NIH syndrome (Not Invented Here is a disease.]], [[- Linus Torvalds]] },
    {
        [[A lot of people still like Solaris, but I'm in active competition with them, and so I hope they die.]],
        [[- Linus Torvalds]],
    },
    {
        [[2.6.<odd>: still a stable kernel, but accept bigger changes leading up to it (timeframe: a month or]],
        [[two).]],
        [[- Linus Torvalds]],
    },
    {
        [[It was *such* a relief to program in user mode for a change. Not having to care about the small stuff is]],
        [[wonderful.]],
        [[- Linus Torvalds]],
    },
    { [[Don't bother. Bram doesn't know what he's talking about.]], [[- Linus Torvalds]] },
    {
        [[Which mindset is right? Mine, of course. People who disagree with me are by definition crazy. (Until I change]],
        [[my mind, when they can suddenly become upstanding citizens. I'm flexible, and not black-and-white.)]],
        [[- Linus Torvalds]],
    },
    {
        [[I chose 1000 originally partly as a way to make sure that people that assumed HZ was 100 would get a swift]],
        [[kick in the pants.]],
        [[- Linus Torvalds]],
    },
    { [[I'm always right. This time I'm just even more right than usual.]], [[- Linus Torvalds]] },
    {
        [[The fact that ACPI was designed by a group of monkeys high on LSD, and is some of the worst designs in the]],
        [[industry obviously makes running it at *any* point pretty damn ugly.]],
        [[- Linus Torvalds]],
    },
    { [[I personally just encourage people to switch to KDE.]], [[- Linus Torvalds]] },
    {
        [[Now, most of you are probably going to be totally bored out of your minds on Christmas day, and here's the]],
        [[perfect distraction. Test 2.6.15-rc7. All the stores will be closed, and there's really nothing better to do in]],
        [[between meals.]],
        [[- Linus Torvalds]],
    },
    {
        [[For example, the GPLv2 in no way limits your use of the software. If you're a mad scientist, you can use]],
        [[GPLv2'd software for your evil plans to take over the world ("Sharks with lasers on their heads!!"), and the]],
        [[GPLv2 just says that you have to give source code back. And that's OK by me. I like sharks with lasers. I just]],
        [[want the mad scientists of the world to pay me back in kind. I made source code available to them, they have to]],
        [[make their changes to it available to me. After that, they can fry me with their shark-mounted lasers all they]],
        [[want.]],
        [[- Linus Torvalds]],
    },
    { [[I claim that Mach people (and apparently FreeBSD) are incompetent idiots.]], [[- Linus Torvalds]] },
    {
        [[I like colorized diffs, but let's face it, those particular color choices will make most people decide to pick]],
        [[out their eyes with a fondue fork.]],
        [[- Linus Torvalds]],
    },
    {
        [[…git actually has a simple design, with stable and reasonably well-documented data structures. In fact, I'm a]],
        [[huge proponent of designing your code around the data, rather than the other way around, and I think it's one of]],
        [[the reasons git has been fairly successful \[…] I will, in fact, claim that the difference between a bad]],
        [[programmer and a good one is whether he considers his code or his data structures more important. Bad]],
        [[programmers worry about the code. Good programmers worry about data structures and their relationships.]],
        [[- Linus Torvalds]],
    },
    {
        [[I think people can generally trust me, but they can trust me exactly because they know they don't *have*]],
        [[to.]],
        [[- Linus Torvalds]],
    },
    {
        [[… even if the Hurd didn't depend on Linux code (and as far as I know, it does, but since I think they have]],
        [[their design heads firmly up their \*sses anyway with that whole microkernel thing, I've never felt it was worth]],
        [[my time even looking at their code), I don't believe a religiously motivated development community can ever]],
        [[generate as good code except by pure chance.]],
        [[- Linus Torvalds]],
    },
    {
        [[I'm a huge believer in evolution (not in the sense that "it happened" – anybody who doesn't believe that is]],
        [[either uninformed or crazy, but in the sense "the processes of evolution are really fundamental, and should]],
        [[probably be at least *thought* about in pretty much any context").]],
        [[- Linus Torvalds]],
    },
    { [[Friends don't let friends use [gcc] "-W".]], [[- Linus Torvalds]] },
    {
        [[It's one of those rare "perfect" kernels. So if it doesn't happen to compile with your config (or it does]],
        [[compile, but then does unspeakable acts of perversion with your pet dachshund), you can rest easy knowing that]],
        [[it's all your own damn fault, and you should just fix your evil ways.]],
        [[- Linus Torvalds]],
    },
    {
        [[Me, I just don't care about proprietary software. It's not "evil" or "immoral," it just doesn't matter. I]],
        [[think that Open Source can do better, and I'm willing to put my money where my mouth is by working on Open]],
        [[Source, but it's not a crusade – it's just a superior way of working together and generating code.]],
        [[- Linus Torvalds]],
    },
    {
        [[Nobody actually creates perfect code the first time around, except me. But there's only one of me.]],
        [[- Linus Torvalds]],
    },
    {
        [[If you have ever done any security work – and it did not involve the concept of "network of trust" – it wasn't]],
        [[security work, it was – masturbation. I don't know what you were doing. But trust me, it's the only way you can]],
        [[do security, it's the only way you can do development.]],
        [[- Linus Torvalds]],
    },
    {
        [[So the whole "We have a list and we're not telling you" should tell you something. Don't you think that if]],
        [[Microsoft actually had some really foolproof patent, they'd just tell us and go, "nyaah, nyaah, nyaah!"?]],
        [[- Linus Torvalds]],
    },
    {
        [[I don't ask for money. I don't ask for sexual favors. I don't ask for access to the hardware you design and]],
        [[sell. I just ask for the thing I gave you: source code that I can use myself.]],
        [[- Linus Torvalds]],
    },
    {
        [[I'm an egotistical bastard, and I name all my projects after myself. First Linux, now git.]],
        [[- Linus Torvalds]],
    },
    {
        [[You try to claim that the GPLv3 causes "More developers", and that, my idiotic penpal, is just crazy talk that]],
        [[you made up.]],
        [[- Linus Torvalds]],
    },
    { [[I have an ego the size of a small planet, but I'm not \_always_ right \[...].]], [[- Linus Torvalds]] },
    { [[Is "I hope you all die a painful death" too strong?]], [[- Linus Torvalds]] },
    { [[It has nothing to do with dinosaurs. Good taste doesn't go out of style]], [[- Linus Torvalds]] },
    {
        [[Yes, I realize that there's a lot of insane people out there. However, we generally don't do kernel design]],
        [[decisions based on them. But we can pat the insane users on the head and say "we won't guarantee it works, but]],
        [[if you eat your prozac, and don't bother us, go do your stupid things".]],
        [[- Linus Torvalds]],
    },
    {
        [[Controlling a laser with Linux is crazy, but everyone in this room is crazy in his own way. So if you want to]],
        [[use Linux to control an industrial welding laser, I have no problem with your using `PREEMPT_RT`.]],
        [[- Linus Torvalds]],
    },
    {
        [[I think Leopard is a much better system \[than Windows Vista] … but OS X in some ways is actually worse than]],
        [[Windows to program for. Their file system is complete and utter crap, which is scary.]],
        [[- Linus Torvalds]],
    },
    { [[And what's the Internet without the rick-roll?]], [[- Linus Torvalds]] },
    {
        [[Security people are often the black-and-white kind of people that I can't stand. I think the OpenBSD crowd is]],
        [[a bunch of masturbating monkeys, in that they make such a big deal about concentrating on security to the point]],
        [[where they pretty much admit that nothing else matters to them.]],
        [[- Linus Torvalds]],
    },
    {
        [[It's what I call "mental masturbation", when you engage is some pointless intellectual exercise that has no]],
        [[possible meaning.]],
        [[- Linus Torvalds]],
    },
    {
        [[Sometimes "`pi = 3.14`" is (a) infinitely faster than the "correct" answer and (b) the difference between the]],
        [["correct" and the "wrong" answer is meaningless. And this is why I get upset when somebody dismisses performance]],
        [[issues based on "correctness". The thing is, some specious value of "correctness" is often irrelevant because it]],
        [[doesn't matter. While performance almost *always* matters. And I absolutely *detest* the fact that people so]],
        [[often dismiss performance concerns so readily.]],
        [[- Linus Torvalds]],
    },
    {
        [[Real quality means making sure that people are proud of the code they write, that they're involved and taking]],
        [[it personally.]],
        [[- Linus Torvalds]],
    },
    {
        [[The fact is, there aren't just two sides to any issue, there's almost always a range of responses, and "it]],
        [[depends" is almost always the right answer in any big question.]],
        [[- Linus Torvalds]],
    },
    {
        [[Your problem has nothing to do with git, and everything to do with emacs. And then you have the *gall* to]],
        [[talk about "Unix design" and not gumming programs together, when you yourself use the most gummed-up]],
        [[piece of absolute sh\*t there is!]],
        [[- Linus Torvalds]],
    },
    {
        [[The thing that has always disturbed me about O\_DIRECT is that the whole interface is just stupid, and was]],
        [[probably designed by a deranged monkey on some serious mind-controlling substances \[\*].]],
        [[- Linus Torvalds]],
    },
    { [[Your code is shit.]], [[- Linus Torvalds]] },
    {
        [[Crying that it's an application bug is like crying over the speed of light: you should deal with *reality*,]],
        [[not what you wish reality was.]],
        [[- Linus Torvalds]],
    },
    {
        [[I may make jokes about Microsoft at times, but at the same time, I think the Microsoft hatred is a disease.]],
        [[- Linus Torvalds]],
    },
    {
        [[There are "extremists" in the free software world, but that's one major reason why I don't call what I do]],
        [["free software" any more. I don't want to be associated with the people for whom it's about exclusion and]],
        [[hatred.]],
        [[- Linus Torvalds]],
    },
    { [[Your argument is shit.]], [[- Linus Torvalds]] },
    {
        [[Every time I see some piece of medical research saying that caffeine is good for you, I high-five myself.]],
        [[Because I'm going to live forever.]],
        [[- Linus Torvalds]],
    },
    {
        [[Standards are paper. I use paper to wipe my butt every day. That's how much that paper is worth.]],
        [[- Linus Torvalds]],
    },
    { [[Toto, I don't think we're talking white-socks-and-sandals any more.]], [[- Linus Torvalds]] },
    { [[This whole ARM thing is a f\*cking pain in the ass.]], [[- Linus Torvalds]] },
    {
        [[Why don't we write code that just works? Or absent a "just works" set of patches, why don't we revert to code]],
        [[that has years of testing? This kind of "I broke things, so now I will jiggle things randomly until they]],
        [[unbreak" is not acceptable. \[...] Don't just make random changes. There really are only two acceptable models]],
        [[of development: "think and analyze" or "years and years of testing on thousands of machines". Those two really]],
        [[do work.]],
        [[- Linus Torvalds]],
    },
    {
        [[So here's a plea: if you have anything to do with security in a distro, and think that my kids (replace "my]],
        [[kids" with "sales people on the road" if you think your main customers are businesses) need to have the root]],
        [[password to access some wireless network, or to be able to print out a paper, or to change the date-and-time]],
        [[settings, please just kill yourself now. The world will be a better place.]],
        [[- Linus Torvalds]],
    },
    {
        [[We're not masturbating around with some research project. We never were. Even when Linux was young, the whole]],
        [[and only point was to make a \*usable* system. It's why it's not some crazy drug-induced microkernel or other]],
        [[random crazy thing.]],
        [[- Linus Torvalds]],
    },
    {
        [[Of course, I'd also suggest that whoever was the genius who thought it was a good idea to read things ONE]],
        [[F\*CKING BYTE AT A TIME with system calls for each byte should be retroactively aborted. Who the f\*ck does]],
        [[idiotic things like that? How did they not die as babies, considering that they were likely too stupid to find a]],
        [[tit to suck on?]],
        [[- Linus Torvalds]],
    },
    {
        [[People say that you should not micro-optimize; but, if what you love is micro-optimization, that's what you]],
        [[should do.]],
        [[- Linus Torvalds]],
    },
    {
        [[I started Linux as a desktop operating system. And it's the only area where Linux hasn't completely taken]],
        [[over. That just annoys the hell out of me.]],
        [[- Linus Torvalds]],
    },
    { [[Nvidia has been the single worst company we've ever dealt with. So, Nvidia, fuck you!]], [[- Linus Torvalds]] },
    { [[I wish everybody was as nice as I am.]], [[- Linus Torvalds]] },
    {
        [[I tend to call myself an anti-visionary because to me, what is much more important than vision is execution.]],
        [[I've always quoted Edison saying that genius is 99% perspiration and 1% inspiration \[...].]],
        [[- Linus Torvalds]],
    },
    {
        [[I like offending people, because I think people who get offended *should* be offended.]],
        [[- Linus Torvalds]],
    },
    {
        [[Somebody is trying to kill all the kernel developers.]],
        [[First we had two earthquakes - fine, this week God not only hates republicans, but apparently us kernel]],
        [[developers too. But we kernel developers laugh in the face of danger, and a 5.5 earthquake just makes us]],
        [[whimper and hide in the closet for a while., But after we've stopped cowering in the closet, there's a knock]],
        [[on the door, and the conference organizers are handing out skate boards, with the innocent explanations of]],
        [["We're in San Diego, after all". If that's not a sign of somebody trying to kill us, I don't know what is.]],
        [[Handing out skate boards to a bunch of geeks sounds like a seriously misguided thing to do.]],
        [[- Linus Torvalds]],
    },
    {
        [[Obsessing about things is important, and things really do matter, but if you can't let go of them, you'll end]],
        [[up crazy.]],
        [[- Linus Torvalds]],
    },
    { [[I'm not sentimental. Good riddance.]], [[- Linus Torvalds]] },
    { [[WE DO NOT BREAK USERSPACE!]], [[- Linus Torvalds]] },
    {
        [[I realize that lawyers are brought up (probably from small children) to think that "technically true" is what]],
        [[matters, but when you make public PR statements, they should be more than "technically" true. They should be]],
        [[honest. There's a big f\*cking difference.]],
        [[- Linus Torvalds]],
    },
    { [[Microsoft isn't evil, they just make really crappy operating systems.]], [[- Linus Torvalds]] },
    {
        [[But this is definitely another of those "This is our most desperate hour. Help me, Al-biwan Ke-Viro, you're my]],
        [[only hope" issues. Al? Please don't make me wear that golden bikini.]],
        [[- Linus Torvalds]],
    },
    { [[I hope I won't end up having to hunt you all down and kill you in your sleep.]], [[- Linus Torvalds]] },
    {
        [[Whoever came up with "hold the shift key for eight seconds to turn on 'your keyboard is buggered' mode" should]],
        [[be shot.]],
        [[- Linus Torvalds]],
    },
    {
        [[There aren't enough swear-words in the English language, so now I'll have to call you perkeleen vittupää just]],
        [[to express my disgust and frustration with this crap.]],
        [[- Linus Torvalds]],
    },
    {
        [[That's the spirit. Greg has taught you well. You have controlled your fear. Now, release your anger. Only your]],
        [[hatred can destroy me. Come to the dark side, Sarah. We have cookies.]],
        [[- Linus Torvalds]],
    },
    {
        [[Because if you want me to "act professional", I can tell you that I'm not interested. I'm sitting in my home]],
        [[office wearing a bathrobe. The same way I'm not going to start wearing ties, I'm \*also* not going to buy into]],
        [[the fake politeness, the lying, the office politics and backstabbing, the passive aggressiveness, and the]],
        [[buzzwords. Because THAT is what "acting professionally" results in: people resort to all kinds of really nasty]],
        [[things because they are forced to act out their normal urges in unnatural ways.]],
        [[- Linus Torvalds]],
    },
    {
        [[Lookie here, your compiler does some absolutely insane things with the spilling, including spilling a]],
        [[\*constant\*. For chrissake, that compiler shouldn't have been allowed to graduate from kindergarten. We're]],
        [[talking "sloth that was dropped on the head as a baby" level retardation levels here.]],
        [[- Linus Torvalds]],
    },
    {
        [[I don't respect people unless I think they deserve the respect. There are people who think that respect is]],
        [[something that should be given, and I happen to be one of the people who is perfectly happy saying no; respect]],
        [[should be earned. And without being earned, you don't get it. It's really that simple.]],
        [[- Linus Torvalds]],
    },
    {
        [[One of the things, none of the distributions have ever done right is application packaging \[...] making]],
        [[binaries for linux desktop applications is a major fucking pain in the ass.]],
        [[- Linus Torvalds]],
    },
    {
        [[I may be a huge computer nerd, but even so I don't think education should be about computers. Not as a]],
        [[subject, and not as a classroom resource either.]],
        [[- Linus Torvalds]],
    },
    { [[On the internet nobody can hear you being subtle.]], [[- Linus Torvalds]] },
    { [[I don’t care about you.]], [[- Linus Torvalds]] },
    {
        [["the most important part of open source is that people are allowed to do what they are good at" and "all that]],
        [[\[diversity] stuff is just details and not really important."]],
        [[- Linus Torvalds]],
    },
    {
        [[I am a lazy person, which is why I like open source, for other people to do work for me.]],
        [[- Linus Torvalds]],
    },
    {
        [[We don't merge kernel code just because user space was written by a retarded monkey on crack.]],
        [[- Linus Torvalds]],
    },
    {
        [[Christ, people. Learn C, instead of just stringing random characters together until it compiles (with]],
        [[warnings).]],
        [[- Linus Torvalds]],
    },
    { [[Get rid of it. And I don't \*ever* want to see that shit again.]], [[- Linus Torvalds]] },
    {
        [[I've actually felt slightly uncomfortable at TED for the last two days, because there's a lot of vision going]],
        [[on, right? And I am not a visionary. I do not have a five-year plan. I'm an engineer. And I think it's really --]],
        [[I mean -- I'm perfectly happy with all the people who are walking around and just staring at the clouds and]],
        [[looking at the stars and saying, "I want to go there." But I'm looking at the ground, and I want to fix the]],
        [[pothole that's right in front of me before I fall in. This is the kind of person I am.]],
        [[- Linus Torvalds]],
    },
    {
        [[I was 21 at the time, so I was young, but I had already programmed for half my life, basically. And every]],
        [[project before that had been completely personal and it was a revelation when people just started commenting,]],
        [[started giving feedback on your code. And even before they started giving code back, that was, I think, one of]],
        [[the big moments where I said, "I love other people!" Don't get me wrong -- I'm actually not a people person.]],
        [[- Linus Torvalds]],
    },
    {
        [[The desktop hasn't really taken over the world like Linux has in many other areas, but just looking at my own]],
        [[use, my desktop looks so much better than I ever could have imagined. Despite the fact that I'm known for]],
        [[sometimes not being very polite to some of the desktop UI people, because I want to get my work done. Pretty is]],
        [[not my primary thing. I actually am very happy with the Linux desktop, and I started the project for my own]],
        [[needs, and my needs are very much fulfilled. That's why, to me, it's not a failure. I would obviously love for]],
        [[Linux to take over that world too, but it turns out it's a really hard area to enter. I'm still working on it.]],
        [[It's been 25 years. I can do this for another 25. I'll wear them down.]],
        [[- Linus Torvalds]],
    },
    {
        [[Lawsuits destroy community. They destroy trust. They would destroy all the goodwill we've built up over the]],
        [[years by being nice.]],
        [[- Linus Torvalds]],
    },
    {
        [[The fact is, the people who have created open source and made it a success have been the developers doing work]],
        [[- and the companies that we could get involved by showing that we are not all insane crazy people like the FSF.]],
        [[The people who have \*destroyed* projects have been lawyers that claimed to be out to "save" those projects.]],
        [[- Linus Torvalds]],
    },
    {
        [[I've been personally pretty disappointed with ARM as a hardware platform, not as an instruction set, though]],
        [[I've had my issues there, too. \[...] What I wanted to upgrade to was Acorn Archimedes ... the thing that gave]],
        [[ARM its name.]],
        [[- Linus Torvalds]],
    },
    {
        [[None of this "there is no way to continue" bullshit. Because it is pure and utter SHIT.]],
        [[- Linus Torvalds]],
    },
    {
        [[BULLSHIT. Have you \_looked_ at the patches you are talking about? You should have - several of them bear your]],
        [[name. \[...] As it is, the patches are COMPLETE AND UTTER GARBAGE. \[...] WHAT THE F\*CK IS GOING ON?]],
        [[- Linus Torvalds]],
    },
    {
        [[It looks like the IT security world has hit a new low. If you work in security, and think you have some]],
        [[morals, I think you might want to add the tag-line "No, really, I'm not a whore. Pinky promise" to your business]],
        [[card. Because I thought the whole industry was corrupt before, but it's getting ridiculous. At what point will]],
        [[security people admit they have an attention-whoring problem?]],
        [[- Linus Torvalds]],
    },
    {
        [[Can I just once again state my love for it and hope it gets merged soon? Maybe the code isn't perfect, but]],
        [[I've skimmed it, and compared to the horrors that are OpenVPN and IPSec, it's a work of art.]],
        [[- Linus Torvalds]],
    },
    {
        [[This is my reality. I am not an emotionally empathetic kind of person and that probably doesn't come as a big]],
        [[surprise to anybody. Least of all me. The fact that I then misread people and don't realize (for years) how]],
        [[badly I've judged a situation and contributed to an unprofessional environment is not good. This week people in]],
        [[our community confronted me about my lifetime of not understanding emotions. My flippant attacks in emails have]],
        [[been both unprofessional and uncalled for. Especially at times when I made it personal. In my quest for a better]],
        [[patch, this made sense to me. I know now this was not OK and I am truly sorry.]],
        [[- Linus Torvalds]],
    },
    {
        [[Don't use ZFS. It's that simple. It was always more of a buzzword than anything else, I feel, and the]],
        [[licensing issues just make it a non-starter for me.]],
        [[- Linus Torvalds]],
    },
    {
        [[You don't know what you are talking about, you don't know what mRNA is, and you're spreading idiotic lies.]],
        [[Maybe you do so unwittingly, because of bad education. Maybe you do so because you've talked to "experts" or]],
        [[watched youtube videos by charlatans that don't know what they are talking about. But dammit, regardless of]],
        [[where you have gotten your mis-information from, any Linux kernel discussion list isn't going to have your]],
        [[idiotic drivel pass uncontested from me. \[...] Get vaccinated. Stop believing the anti-vax lies. And if you]],
        [[insist on believing in the crazy conspiracy theories, at least SHUT THE HELL UP about it on Linux kernel]],
        [[discussion lists.]],
        [[- Linus Torvalds]],
    },
    {
        [[I know most of us are preparing for Christmas, but give it a whirl, ok? How important are those presents (and]],
        [[that family) anyway?]],
        [[- Linus Torvalds]],
    },
    {
        [[Please, as you emerge from your holiday-induced food coma, do give it a quick test so that we can all be happy]],
        [[about the final release next weekend.]],
        [[- Linus Torvalds]],
    },
    {
        [[...today, March 14th, is the 29th anniversary of the Linux 1.0 announcement. Of course, there are other]],
        [[arguably more important dates in Linux history, but this is *one* of them.]],
        [[- Linus Torvalds]],
    },
    {
        [[I’m actually a horrible MIS person, and I would never want to maintain my own server. I’m a programmer for]],
        [[chrissake! The same way you should fear me if I hold a soldering iron, you should be very very nervous if I were]],
        [[to do any server management... and on a similar note: not only am I not much of a MIS person, I’m also not much]],
        [[of a social networking person. I foresee a lot of disappointment in the future of any followers of this]],
        [[account.]],
        [[- Linus Torvalds]],
    },
    {
        [[It’s Caturday. Minky is no longer with us, but this is probably my favorite picture of her.]],
        [[- Linus Torvalds]],
    },
    {
        [[It’s Sunday, which means no more cat pictures, and instead just the usual -rc release. Prize for odd bug this]],
        [[week goes to an otherwise harmless off-by-one buglet that then in turn confused clang sufficiently to generate]],
        [[bogus code that our ‘objtool’ checks then (correctly) complained about it. This is the kind of exciting lives]],
        [[that us kernel developers lead.]],
        [[- Linus Torvalds]],
    },
    {
        [[Pet peeve of the day: all the people talking about how ChatGPT is not “conscious” and how it does not]],
        [[“understand” what it is saying, but just putting likely-sounding words together into likely-sounding sentences.]],
        [[Extra bonus points for using an example of a math problem as a way to show how these AI chat-bots talk about]],
        [[things they don’t really understand. The irony. The lack of self-awareness. It burns.]],
        [[- Linus Torvalds]],
    },
    {
        [[Sometimes you have one of those days that just shows how incompetent you are... Moral of the day: RTFM.]],
        [[- Linus Torvalds]],
    },
    {
        [[I’ve maintained a branch of the old micro-emacs (*not* GNU emacs) for decades. And by “maintained” I really]],
        [[mean “mostly kept working”. It’s a scrappy little editor from the eighties(!) and the “s” in scrappy is]],
        [[silent... Over the decades, I’ve “enhached” that thing to actually mostly understand UTF-8, and increased some]],
        [[internal limits, but it’s mostly the same thing that I used in the early nineties... I don’t love the fact that]],
        [[it’s a very limited text editor. I’d *like* syntax highlighting etc. But my fingers are absolutely hardcoded to]],
        [[it, and I am not in the least interested in something that makes me switch away from those (much less start]],
        [[using a *mouse* to move around etc). Which is just a very long way to say: “Does anybody know of some slightly]],
        [[more modern GUI editor that actually has good support for really changing keybindings”... And yes, I know one]],
        [[answer is “teach your fingers new ways”. But my micro-emacs works just fine, and so it really isn’t worth it to]],
        [[me... I’d rather maintain just a keybinding file than a whole scrappy editor... I’m not interested in yet]],
        [[another “runs in a terminal” editor, or some even older editor (ie “real” emacs, or vim) that just has had more]],
        [[lipstick applied over the years.]],
        [[- Linus Torvalds]],
    },
    {
        [[It's Easter Sunday, which means that we're all about to gorge on mämmi (Right? You \*do* have your carton of]],
        [[mämmi ready to go, don't you?).]],
        [[- Linus Torvalds]],
    },
    {
        [[Life is good. We have a dishwasher again. Our old one broke (again!) and while I fixed it myself last time, I]],
        [[wasn’t willing to deal with a dishwasher that keeps breaking. I grew up washing dishes by hand, and I’d largely]],
        [[forgotten how much I hated it. Ten days without a working dishwasher is ten days too many.]],
        [[- Linus Torvalds]],
    },
    {
        [[I’m a card-carrying atheist, I think a woman’s right to choose is very important, I think that “well regulated]],
        [[militia” means that guns should be carefully licensed and not just randomly given to any moron with a pulse, and]],
        [[I couldn’t care less if you decided to dress up in the “wrong” clothes or decided you’d rather live your life]],
        [[without feeling tied to whatever plumbing you were born with. And dammit, if that all makes me “woke”, then I]],
        [[think anybody who uses that word as a pejorative is a f\*cking disgrace to the human race. So please just]],
        [[unfollow me right now.]],
        [[- Linus Torvalds]],
    },
    {
        [[I will now go back to my cave and continue pulling stuff, I just had to do something else for a while. Some]],
        [[people relax with a nice drink by the pool, I relax by playing around with inline asm.]],
        [[- Linus Torvalds]],
    },
    {
        [[The day we finally get rid of HIGHMEM I will dance on its grave. I have hated that thing for a long long]],
        [[time.]],
        [[- Linus Torvalds]],
    },
    {
        [[A third of a century. And it \*still* isn't ready. I really need to get my sh\*t together..]],
        [[- Linus Torvalds]],
    },
    {
        [[You're a smart person. I feel like I've given you enough hints. Why don't you sit back and think about it, and]],
        [[let's make it clear: you have exactly two choices here:]],
        [[(a) play better with others]],
        [[(b) take your toy and go home]],
        [[Those are the choices.]],
        [[- Linus Torvalds]],
    },
    {
        [[If you haven't heard of Russian sanctions yet, you should try to read the news some day. And by "news", I]],
        [[don't mean Russian state-sponsored spam. As to sending me a revert patch - please use whatever mush you call]],
        [[brains. I'm Finnish. Did you think I'd be \*supporting* Russian aggression? Apparently it's not just lack of]],
        [[real news, it's lack of history knowledge too.]],
        [[- Linus Torvalds]],
    },
    {
        [[Finally, I have a firm belief that most firmware developers are not actually humans, but are instead caged]],
        [[rodents fed a solid diet of crack cocaine. Because that would explain a lot.]],
        [[- Linus Torvalds]],
    },
    {
        [[How about you accept the fact that maybe the problem is you. You think you know better. But the current]],
        [[process works. It has problems, but problems are a fact of life. There is no perfect.]],
        [[- Linus Torvalds]],
    },
    {
        [[And no, I am not looking for yes-men, and I like it when you call me out on my bullshit. I say some stupid]],
        [[things at times, there needs to be people who just stand up to me and tell me I'm full of shit.]],
        [[- Linus Torvalds]],
    },
    {
        [[But I much prefer other people solving my problems for me. So me having to come up with a project is actually]],
        [[a failure of the world—and the world just hasn’t failed in the last 20 years for me.]],
        [[- Linus Torvalds]],
    },
    {
        [[I'm told that there are people claiming to "tokenize" my git repositories with my approval. I just want to]],
        [[clarify that that is not the case. I do not believe in monetizing my repositories. If you believe]],
        [[crypto-currencies are anything but a scam, I have a bridge to sell you. But I'm not selling source code.]],
        [[- Linus Torvalds]],
    },
    {
        [[It's memorial day tomorrow here in the US, but like the USPS, "neither snow nor rain nor heat nor gloom of]],
        [[night" - nor memorial day - stops the merge window.]],
        [[- Linus Torvalds]],
    },
    { [[People are strange, and you can't fix people.]], [[- Linus Torvalds]] },
    {
        [[*If 386BSD had been available when I started on Linux, Linux would probably never had happened.*]],
        [[- Linus Torvalds]],
    },
    { [[Software is like sex; it's better when it's free.]], [[- Linus Torvalds]] },
    { [[The memory management on the PowerPC can be used to frighten small children.]], [[- Linus Torvalds]] },
    {
        [[OK, I admit it. I was just a front-man for the real fathers of Linux, the Tooth Fairy and Santa Claus.]],
        [[- Linus Torvalds]],
    },
    {
        [[Guess what? Wheels have been round for a really long time, and anybody who "reinvents" the new wheel is]],
        [[generally considered a crackpot. It turns out that "round" is simply a good form for a wheel to have. It may be]],
        [[boring, but it just tends to roll better than a square, and "hipness" has nothing what-so-ever to do with it.]],
        [[- Linus Torvalds]],
    },
    {
        [[I don't doubt at all that virtualization is useful in some areas. What I doubt rather strongly is that it will]],
        [[ever have the kind of impact that the people involved in virtualization want it to have.]],
        [[- Linus Torvalds]],
    },
    {
        [[First off, I'm actually perfectly well off. I live in a good-sized house, with a nice yard, with deer]],
        [[occasionally showing up and eating the roses (my wife likes the roses more, I like the deer more, so we don't]],
        [[really mind). I've got three kids, and I know I can pay for their education. What more do I need? The thing is,]],
        [[being a good programmer actually pays pretty well; being acknowledged as being world-class pays even better. I]],
        [[simply didn't need to start a commercial company. And it's just about the least interesting thing I can even]],
        [[imagine. I absolutely hate paperwork. I couldn't take care of employees if I tried. A company that I started]],
        [[would never have succeeded – it's simply not what I'm interested in! So instead, I have a very good life, doing]],
        [[something that I think is really interesting, and something that I think actually matters for people, not just]],
        [[me. And that makes me feel good.]],
        [[- Linus Torvalds]],
    },
    {
        [[So LSM stays in. No ifs, buts, maybes or anything else. When I see the security people making sane arguments]],
        [[and agreeing on something, that will change. Quite frankly, I expect hell to freeze over before that happens,]],
        [[and pigs will be nesting in trees. But hey, I can hope.]],
        [[- Linus Torvalds]],
    },
    {
        [[So I would not be surprised if the globbing libraries, for example, will do NFD-mangling in order to glob]],
        [["correctly", so even programs ported from real Unix might end up getting pathnames subtly changed into NFD as]],
        [[part of some hot library-on-library action with UTF hackery inside.]],
        [[- Linus Torvalds]],
    },
    { [[Portability is for people who cannot write new programs.]], [[- Linus Torvalds]] },
    { [[Dijkstra probably hates me.]], [[- Linus Torvalds]] },
    { [[EFI is this other Intel brain-damage (the first one being ACPI.]], [[- Linus Torvalds]] },
    { [[Gcc is crap.]], [[- Linus Torvalds]] },
    {
        [[C++ is a horrible language. It's made more horrible by the fact that a lot of substandard programmers use it,]],
        [[to the point where it's much much easier to generate total and utter crap with it.]],
        [[- Linus Torvalds]],
    },
    {
        [[C++ is in that inconvenient spot where it doesn't help make things simple enough to be truly usable for]],
        [[prototyping or simple GUI programming, and yet isn't the lean system programming language that C is that]],
        [[actively encourages you to use simple and direct constructs.]],
        [[- Linus Torvalds]],
    },
    {
        [[XML is crap. Really. There are no excuses. XML is nasty to parse for humans, and it's a disaster to parse even]],
        [[for computers. There's just no reason for that horrible crap to exist.]],
        [[- Linus Torvalds]],
    },
}
