-- these qoutes were not checked cz I know them by heart....
return {
    { "I used to be an adventurer like you, until I took an arrow in the knee." },
    { "Do you get to the cloud district very often? Oh what am I saying, of course you don't" },
    { "Some may call these junk. Me? I call them treasures." },
    {
        "We're fighting because we're done bleeding for an Empire that won't bleed for us.",
        "Untold numbers of Nords died defending the Empire against the Dominion. And for what?",
        "Skyrim being sold to the Thalmor so the Emperor could keep his throne!",
        "We're fighting because our own Jarls, once strong, wise men, have become fearful and blind to their people's suffering.",
        "We're fighting because Skyrim needs heroes, and there's no one else but us.",
    },
    {
        "I fight for the men I've held in my arms, dying on foreign soil.",
        "I fight for their wives and children, who's names I heard whispered in their last breaths.",
        "I fight for we few who did come home, only to find our country full of strangers wearing familiar faces.",
        "I fight for my people impoverished to pay the debts of an Empire too weak to rule them, yet brands them criminals for wanting to rule themselves!",
        "I fight so that all the fighting I've already done hasn't been for nothing.",
        "I fight... because I must.",
    },
    {
        "This is it men! It's time to make this city ours! We come to this moment carried by the sacrifices and the courage of our fellows.",
        "Those who have fallen. And those still bearing the shields to our right.",
        "On this day, our enemy will know the fullness of our determination, the true depth of our anger, and the exalted righteousness of our cause.",
        "The gods are watching. The spirits of our ancestors are stirring.",
        "And the men under suns yet to dawn will be transformed by what we do here today. Fear neither pain, nor darkness.",
        "For Sovngarde awaits those who die with weapons in their hands, and courage in their hearts.",
        "We now fight our way to Castle Dour to cut the head off the legion itself!",
        "And in that moment, the gods will look down and see Skyrim as she was meant to be.",
        "Full of Nords who are mighty, powerful, and free! Ready now! Everyone, with me! For the sons and daughters of Skyrim!",
    },
    { "What is better? to be born good? Or to overcome your evil nature through great effort?" },
    { "You'll make a fine rug, cat!" },
    { "Whoa, whoa, whoa, watch the magic!" },
    {
        "Ho ho ho and hee hee hee, break that lute across my knee. And if the bard should choose to fight, why then I set his clothes alight",
    },
    { "And he says to the man, ‘That’s not a horker! That’s my wife!" },
    { "Psst! Hey! I know who you are! Hail Sithis!" },
    { "Let me guess. Someone stole your sweet roll!" },
    { "Heard about you and your honeyed words." },
    { "Watch the skies, traveler" },
    { "Sky above, voice within." },
}
